# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Gaston Sanchez
url:              http://gastonsanchez.com
baseurl:          /

author:
  name:           'Gaston Sanchez'
  url:            http://gastonsanchez.com

paginate:         5

# Custom vars
version:          cc-by-sa

github:
  repo:           https://github.com/gastonstat
